<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jalaldeveloper.accountingsystem</groupId>
        <artifactId>accounting-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>accounting-container</artifactId>
    <name>accounting-container</name>
    <description>Spring Boot application container for accounting modular monolith</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>accounting-domain-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>accounting-application-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>accounting-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>accounting-dataaccess</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>accounting-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>common-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>common-platform</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>contacts-application-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>contacts-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>contacts-dataaccess</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>inventory-application-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>inventory-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>inventory-dataaccess</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>purchase-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>purchase-dataaccess</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>sales-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>sales-dataaccess</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.jalaldeveloper.accountingsystem.AccountingServiceApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
