<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jalaldeveloper.accountingsystem</groupId>
        <artifactId>accounting-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>accounting-application</artifactId>
    <name>accounting-application</name>
    <description>REST API layer: controllers, exception handlers</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>accounting-application-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>common-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jalaldeveloper.accountingsystem</groupId>
            <artifactId>accounting-domain-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
