<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>accounting-container</module>
        <module>accounting-dataaccess</module>
        <module>accounting-domain</module>
        <module>accounting-application</module>
        <module>accounting-messaging</module>
    </modules>

    <parent>
        <artifactId>accounting-system</artifactId>
        <groupId>com.jalaldeveloper.accountingsystem</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>accounting-service</artifactId>
    <packaging>pom</packaging>
    <name>accounting-service</name>


</project>
